export type EventoFallback = {
  no: number
  titulo: string
  slug: string
  data: string
  local: string
  facilitador: string
  totalParticipantes: number
  parceiro: string
  duracao: string
  descricaoBreve: string
  status: "passado" | "proximo" | "inscricoes-abertas"
  imagemCapaUrl: string
}

const breve = (
  totalParticipantes: number,
  duracao: string,
  facilitador: string,
  parceiro: string,
) => {
  const p =
    parceiro.trim() === "-" || parceiro.trim() === ""
      ? null
      : `Parceiros: ${parceiro}.`
  return [
    `${totalParticipantes} participantes`,
    duracao,
    `Facilitação: ${facilitador}.`,
    p,
  ]
    .filter(Boolean)
    .join(" ")
}

const ev = (
  args: Omit<EventoFallback, "descricaoBreve" | "status" | "imagemCapaUrl">,
): EventoFallback => ({
  ...args,
  descricaoBreve: breve(
    args.totalParticipantes,
    args.duracao,
    args.facilitador,
    args.parceiro,
  ),
  status: "passado",
  imagemCapaUrl: `/eventos/${args.slug}/capa.png`,
})

export const eventosFallback: EventoFallback[] = [
  ev({
    no: 1,
    titulo: "1.ª Conferência de Liderança Feminina",
    slug: "e01-1-conferencia-lideranca-feminina-2023",
    data: "2023-03-11T12:00:00.000Z",
    local: "Hotel Coimbra, Bissau",
    facilitador: "MiF",
    totalParticipantes: 144,
    parceiro: "Hotel Coimbra, Kenam, Abiptom, Clarity4D",
    duracao: "1 dia",
  }),
  ev({
    no: 2,
    titulo: "Workshop: Perfil Comportamental",
    slug: "e02-workshop-perfil-comportamental-2023",
    data: "2023-03-11T14:00:00.000Z",
    local: "Hotel Coimbra, Bissau",
    facilitador: "Adama Djalo",
    totalParticipantes: 50,
    parceiro: "Clarity4D",
    duracao: "2 horas",
  }),
  ev({
    no: 3,
    titulo: "Workshop: Habilidades Profissionais",
    slug: "e03-workshop-habilidades-profissionais-hotel-2023",
    data: "2023-03-11T16:00:00.000Z",
    local: "Hotel Coimbra, Bissau",
    facilitador: "Ana Djú",
    totalParticipantes: 50,
    parceiro: "-",
    duracao: "2 horas",
  }),
  ev({
    no: 4,
    titulo: "Curso: Habilidades Profissionais",
    slug: "e04-curso-habilidades-profissionais-30",
    data: "2023-07-16T12:00:00.000Z",
    local: "American Corner, Tchico Té",
    facilitador: "Ana Djú",
    totalParticipantes: 30,
    parceiro: "American Corner",
    duracao: "6 semanas",
  }),
  ev({
    no: 5,
    titulo: "Curso: Habilidades Profissionais",
    slug: "e05-curso-habilidades-profissionais-33",
    data: "2023-07-16T12:00:00.000Z",
    local: "American Corner, Tchico Té",
    facilitador: "Ana Djú",
    totalParticipantes: 33,
    parceiro: "American Corner",
    duracao: "6 semanas",
  }),
  ev({
    no: 6,
    titulo: "Bolsas de estudo da língua francesa",
    slug: "e06-bolsas-lingua-francesa-2023",
    data: "2023-11-01T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "MiF",
    totalParticipantes: 10,
    parceiro: "CCFBG",
    duracao: "8 meses",
  }),
  ev({
    no: 7,
    titulo: "Almoço / angariação de fundos",
    slug: "e07-almoco-angariacao-fundos-gamela-2024",
    data: "2024-02-03T12:00:00.000Z",
    local: "GãMela, Bissau",
    facilitador: "MiF",
    totalParticipantes: 30,
    parceiro: "GãMela",
    duracao: "4 horas",
  }),
  ev({
    no: 8,
    titulo: "2.ª Conferência de Liderança Feminina",
    slug: "e08-2-conferencia-lideranca-feminina-2024",
    data: "2024-03-09T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "MiF",
    totalParticipantes: 200,
    parceiro: "CCFBG, Rádio Jovem, No Kunsi Digital",
    duracao: "1 dia",
  }),
  ev({
    no: 9,
    titulo: "Masterclass: Public Speaking",
    slug: "e09-masterclass-public-speaking-ena-2024",
    data: "2024-04-20T12:00:00.000Z",
    local: "ENA, Bissau",
    facilitador: "MiF",
    totalParticipantes: 49,
    parceiro: "ENA",
    duracao: "2 horas",
  }),
  ev({
    no: 10,
    titulo: "3.ª Conferência de Liderança Feminina",
    slug: "e10-3-conferencia-lideranca-feminina-2024",
    data: "2024-03-09T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "MiF",
    totalParticipantes: 185,
    parceiro: "CCFBG, Rádio Jovem, No Kunsi Digital",
    duracao: "1 dia",
  }),
  ev({
    no: 11,
    titulo: "Workshop: Introdução à gestão de projetos",
    slug: "e11-workshop-gestao-projectos-2024",
    data: "2024-06-01T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Tarcísio Correia",
    totalParticipantes: 70,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 12,
    titulo: "Workshop: Public Speaking",
    slug: "e12-workshop-public-speaking-2024",
    data: "2024-06-15T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "MiF",
    totalParticipantes: 64,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 13,
    titulo: "Workshop: Literacia digital",
    slug: "e13-workshop-literacia-digital-2024",
    data: "2024-06-29T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Clayton Correia",
    totalParticipantes: 11,
    parceiro: "CCFBG, Abiptom",
    duracao: "2 horas",
  }),
  ev({
    no: 14,
    titulo: "Workshop: Introdução ao empreendedorismo",
    slug: "e14-workshop-empreendedorismo-2024",
    data: "2024-07-13T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Biljorge Cabral",
    totalParticipantes: 60,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 15,
    titulo: "Workshop: Escrita de CVs e cover letter",
    slug: "e15-workshop-cvs-cover-letter-2024",
    data: "2024-07-27T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "MiF",
    totalParticipantes: 50,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 16,
    titulo: "Workshop: Como criar um perfil de LinkedIn",
    slug: "e16-workshop-linkedin-2024",
    data: "2024-08-10T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Biljorge Cabral",
    totalParticipantes: 50,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 17,
    titulo: "Workshop: Introdução ao Canva",
    slug: "e17-workshop-canva-2024",
    data: "2024-08-24T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Ana Neves",
    totalParticipantes: 50,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 18,
    titulo: "Workshop: Mecanismos de financiamento a jovens",
    slug: "e18-workshop-financiamento-jovens-2024",
    data: "2024-09-07T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Jocelina Mendes Pereira",
    totalParticipantes: 60,
    parceiro: "CCFBG, ActionAid, CICA",
    duracao: "2 horas",
  }),
  ev({
    no: 19,
    titulo: "Workshop: Introdução à gestão de projetos",
    slug: "e19-workshop-gestao-projetos-2024",
    data: "2024-09-14T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Tarcísio Correia",
    totalParticipantes: 50,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 20,
    titulo: "Workshop: Escolhendo uma carreira",
    slug: "e20-workshop-escolhendo-carreira-2024",
    data: "2024-09-28T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Ilsa Cá e Sá",
    totalParticipantes: 50,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 21,
    titulo: "Coquetel: Mulheres guineenses, identidades diaspóricas",
    slug: "e21-coquetel-identidades-diasporicas-2025",
    data: "2025-04-03T18:00:00.000Z",
    local: "Embaixada da França, Bissau",
    facilitador: "MiF",
    totalParticipantes: 30,
    parceiro: "CCFBG, Embaixada da França",
    duracao: "3 horas",
  }),
  ev({
    no: 22,
    titulo: "Programa de mentoria",
    slug: "e22-programa-mentoria-2025",
    data: "2025-08-01T12:00:00.000Z",
    local: "Remoto",
    facilitador: "MiF",
    totalParticipantes: 18,
    parceiro: "CCFBG",
    duracao: "6 meses",
  }),
  ev({
    no: 23,
    titulo: "Workshop: Inteligência emocional",
    slug: "e23-workshop-inteligencia-emocional-2025",
    data: "2025-07-14T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Elise Bidault",
    totalParticipantes: 100,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 24,
    titulo: "Workshop: Saúde sexual e reprodutiva",
    slug: "e24-workshop-saude-sexual-2025-07",
    data: "2025-07-28T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Maria Mendes",
    totalParticipantes: 50,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 25,
    titulo: "Workshop: Educação financeira",
    slug: "e25-workshop-educacao-financeira-2025",
    data: "2025-11-15T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Noella Tavares Bangura",
    totalParticipantes: 60,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 26,
    titulo: "Workshop: Literacia digital",
    slug: "e26-workshop-literacia-digital-2025",
    data: "2025-11-22T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Clayton Correia",
    totalParticipantes: 10,
    parceiro: "iParticipate / Abiptom",
    duracao: "2 horas",
  }),
  ev({
    no: 27,
    titulo: "Workshop: Saúde sexual e reprodutiva",
    slug: "e27-workshop-saude-sexual-2025-11",
    data: "2025-11-29T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "Maria Mendes",
    totalParticipantes: 60,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 28,
    titulo: "Workshop: Falar em público",
    slug: "e28-workshop-falar-em-publico-2026",
    data: "2026-02-21T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "MiF",
    totalParticipantes: 50,
    parceiro: "CCFBG",
    duracao: "2 horas",
  }),
  ev({
    no: 29,
    titulo: "4.ª Conferência de Liderança Feminina",
    slug: "e29-4-conferencia-lideranca-feminina-2026",
    data: "2026-03-07T12:00:00.000Z",
    local: "CCFBG, Bissau",
    facilitador: "MiF",
    totalParticipantes: 297,
    parceiro: "CCFBG, Rádio Jovem, No Kunsi Digital",
    duracao: "1 dia",
  }),
]

export const eventosFallbackOrdenados = [...eventosFallback].sort((a, b) => {
  const t = new Date(b.data).getTime() - new Date(a.data).getTime()
  if (t !== 0) return t
  return a.no - b.no
})
